FROM node:18

WORKDIR /app

# Only copy package files first to leverage Docker cache
COPY package*.json ./

# Install dependencies (inside Docker)
RUN npm install

# Now copy the rest of your app code
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
